export const GLOSSARIO: Record<string, string> = {
  servidor: "Funcionario publico empregado por uma prefeitura. Identidade = CPF + matricula. Tem margem descontavel em folha.",
  matricula: "Identidade empregaticia. Uma pessoa pode ter N matriculas se trabalha em multiplas prefeituras/posicoes.",
  idMatricula: "Id interno do banco para o tuplo (prefeitura, matricula).",
  prefeitura: "Empregador do servidor. Opera folha de pagamento onde parcelas sao descontadas.",
  banco: "Instituicao financeira que oferta consignado. Paga comissao a averbadora.",
  averbadora: "Plataforma central (Atlas). Conecta servidor, prefeitura e banco.",
  simulacao: "Calculo nao-vinculante read-only.",
  proposta: "Oferta formal de um banco. Tem maquina de estados.",
  reserva: "Slot pre-contrato segurado pelo banco. Confirmar -> contrato; nao confirmar -> expira.",
  contrato: "Acordo de emprestimo formal.",
  averbacao: "Registro do desconto da parcela na folha da prefeitura.",
  refinanciamento: "Estender ou reestruturar contrato existente.",
  portabilidade: "Transferir contrato de banco A para banco B. Regulada pelo BACEN 4.292/2013.",
  quitacao: "Pagamento antecipado total do saldo devedor.",
  liberacao: "Credito do dinheiro na conta do servidor (apos averbacao).",
  margem_consignavel: "Maximo % do salario liquido que pode ser descontado em folha (emprestimo = 35%).",
  cet: "Custo Efetivo Total. Inclui taxa + IOF + tarifas. Exigido pelo BACEN.",
  iof: "Imposto sobre Operacoes Financeiras. Aliquota fixa 0,38% + 0,0082%/dia ate 365 dias.",
  tac: "Tarifa de Abertura de Credito. Proibida em consignado publico.",
  carencia: "Periodo de graca antes da primeira parcela.",
  saldo_devedor: "Principal remanescente do contrato.",
  adf: "Identificador unico de contrato/operacao no banco.",
  idConvenio: "Id do convenio entre banco e prefeitura.",
  chaveAcesso: "Chave de sessao emitida pelo banco para operacoes ligadas a matricula.",
  competencia: "Periodo YYYYMM (mes da folha).",
  situacao_funcional: "Status atual do servidor: ATIVO, FERIAS, AFASTADO, LICENCA, APOSENTADO.",
  vinculo_empregaticio: "Tipo de vinculo: CLT, ESTATUTARIO, COMISSIONADO.",
};
